swagger: "2.0"

info:
  version: "1.0.0"
  title: "Property Details API"
  description: "A simple API that returns all the details of Property of given ID"

schemes:
    -"http"
host: "localhost:3001"
basePath: "/api/v1"

paths:
  /properties/{id}:
    get:
      summary: "Get Property"
      description: "Returns list of property Details, trending Projects, similar Properties of that ID"
      parameters:
      - in: "path"
        name: "id"
        required: true
        description: "The Property ID"
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            required:
              - "id"
            properties:
              code:
                type: "number"
              body:
                type: "object"
              o:
                type: "number"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Property not found"
      security:
      - api_key: []
